### ISSUE TITLE
evolution seems to not remember hive killed or incompatibility with shall endgame evolution

### ISSUE THREAD

**Issue by Biviho** [veden/rampantEvolution#2]
sorry, i didn't know how to phrase this.
basically, using shall endgame evolution to check the evolution factor.

for what i can see, while the evolution factor seems to increase and decrease correctly with tile absorption and tree absorption, if an hive is killed, it seems that the evolution factor increases for a brief time to then decrease back to the previous value after something like 10 seconds.

i don't know the tecnicality behind factorio, is it a bug, an incompatibility or something else?

**Comment by veden** [comment]
Give the latest version a try on the mod portal and let me know.
