### ISSUE TITLE
 Evolution %%

### ISSUE THREAD

**Issue by garrotte13** [veden/rampantEvolution#3]
Hi!
Gamesave from mod portal discussion thread https://mods.factorio.com/mod/RampantEvolution/discussion/61c9cfe371e6a25fad0e58b2
[Evo5.zip](https://github.com/veden/rampantEvolution/files/7786571/Evo5.zip)
After loading this save, possibly some waiting (it's up to you), open mod settings and increase evo-per-second-elapsed contribution from 1 to 2. And you'll see how global evo goes down from 12.9% to 4.28% and stays at this value even after 10 minutes waiting.

After big fights with biters, many nests purged I saw that factor contribution (evo-per-spawner-killed) going wild. And after any even small change of mod settings recalculation removed excessive 30% of global evolution with ease.

**Comment by veden** [comment]
This should be fixed in the latest.
Thanks for the save and your time.

**Comment by garrotte13** [comment]
Tested purging some nests. Seems the problem is solved now. Still have questions about those %% units in rampantevolution console output, but better ask them in other thread.
Thank you!
